navbarColorScheme: light
navbarBackgroundColor: default
bootswatchSettings:
  bootswatchThemeCDNLocation: 'https://stackpath.bootstrapcdn.com/bootswatch/4.3.1'
  bootswatchThemeFilename: bootstrap.min.css
  bootswatchThemeName: cerulean
  useBootswatchTheme: false
