forms:
  - formLabel: Contact Form
    formId: contact-form
    formActionUrl: https://docs.google.com/forms/u/0/d/e/1FAIpQLSenSNIEJTxJN2tGx9wwATrmVJPZfvqfGJIRkWxiEchDoRGBrw/formResponse
    formMethod: POST
    formNameAttribute: contactForm
    formAsyncEnabled: true
    formAsyncRequestMode: no-cors
    formControls:
      fields:
        - initialValue: none
          label: Full Name
          nameAttribute: entry.1490771840
          placeholder: Enter your full name
          required: true
          requiredErrorText: This field is required.
          type: text
        - initialValue: none
          label: Email
          nameAttribute: emailAddress
          placeholder: Enter your email
          required: true
          requiredErrorText: This field is required.
          type: email
        - initialValue: none
          label: Message
          nameAttribute: entry.1205850139
          placeholder: Enter your message
          required: true
          requiredErrorText: This field is required.
          type: textarea
      submitButtonText: Send
  - formLabel: Mailing List
    formId: mailing-list
    formActionUrl: https://docs.google.com/forms/u/0/d/e/1FAIpQLSc5s3mOulygCILIycMDrGc8cKBjYBmm22Pxm8NV-9z1hg4PqQ/formResponse
    formMethod: POST
    formNameAttribute: subscriptions
    formAsyncEnabled: true
    formAsyncRequestMode: no-cors
    formControls:
      fields:
        - initialValue: none
          label: Email
          nameAttribute: emailAddress
          placeholder: Enter your email
          required: true
          requiredErrorText: This field is required.
          type: email
      submitButtonText: Send
  - formLabel: Feedback Form
    formId: feedback-form
    formActionUrl: https://docs.google.com/forms/u/0/d/e/1FAIpQLSe-J6w4dTCfveWU8BByodBklIqN4geC4VdtlLdF4IDTa7kyEg/formResponse
    formMethod: POST
    formNameAttribute: feedbackForm
    formAsyncEnabled: true
    formAsyncRequestMode: cors
    formControls:
      fields:
        - initialValue: none
          label: Message
          nameAttribute: entry.1812331578
          placeholder: Enter your message
          required: true
          requiredErrorText: This field is required.
          type: textarea
      submitButtonText: Send