forms:
  - formActionUrl: >-
      https://docs.google.com/forms/u/0/d/e/1FAIpQLSenSNIEJTxJN2tGx9wwATrmVJPZfvqfGJIRkWxiEchDoRGBrw/formResponse
    formAsyncEnabled: true
    formAsyncRequestMode: no-cors
    formControls:
      fields:
        - initialValue: none
          label: Full Name
          nameAttribute: entry.1490771840
          placeholder: Enter your full name
          required: true
          requiredErrorText: This field is required.
          type: text
        - initialValue: none
          label: Email
          nameAttribute: emailAddress
          placeholder: Enter your email
          required: true
          requiredErrorText: This field is required.
          type: email
        - initialValue: none
          label: Message
          nameAttribute: entry.1205850139
          placeholder: Enter your message
          required: true
          requiredErrorText: This field is required.
          type: textarea
        - initialValue: '{siteName}'
          label: Source
          nameAttribute: entry.25341020
          placeholder: Enter this field
          required: false
          requiredErrorText: This field is required.
          type: hidden
      submitButtonText: Send
    formId: contact-form
    formLabel: Contact Form
    formMethod: POST
    formNameAttribute: contactForm
  - formActionUrl: >-
      https://docs.google.com/forms/u/0/d/e/1FAIpQLSc5s3mOulygCILIycMDrGc8cKBjYBmm22Pxm8NV-9z1hg4PqQ/formResponse
    formAsyncEnabled: true
    formAsyncRequestMode: no-cors
    formControls:
      fields:
        - initialValue: none
          label: Email
          nameAttribute: emailAddress
          placeholder: Enter your email
          required: true
          requiredErrorText: This field is required.
          type: email
        - initialValue: '{siteName}'
          label: Source
          nameAttribute: entry.1498947970
          placeholder: Enter this field
          required: false
          requiredErrorText: This field is required.
          type: text
      submitButtonText: Send
    formId: mailing-list
    formLabel: Mailing List
    formMethod: POST
    formNameAttribute: subscriptions
  - formActionUrl: >-
      https://docs.google.com/forms/u/0/d/e/1FAIpQLSe-J6w4dTCfveWU8BByodBklIqN4geC4VdtlLdF4IDTa7kyEg/formResponse
    formAsyncEnabled: true
    formAsyncRequestMode: cors
    formControls:
      fields:
        - initialValue: none
          label: Message
          nameAttribute: entry.1812331578
          placeholder: Enter your message
          required: true
          requiredErrorText: This field is required.
          type: textarea
        - initialValue: '{siteName}'
          label: Source
          nameAttribute: entry.1161101600
          placeholder: Enter this field
          required: false
          requiredErrorText: This field is required.
          type: text
      submitButtonText: Send
    formId: feedback-form
    formLabel: Feedback Form
    formMethod: POST
    formNameAttribute: feedbackForm
