siteIcon: "/media/default-site-icon.png"
siteUrl: https://boldlypress.netlify.com
siteIconAlt: Dots arranged in a spiral pattern.
siteName: BoldlyPress
siteImage: "/media/default-site-image.jpg"
siteDescription: The serverless CMS for React developers.
siteImageAlt: Cute and cuddly kittens.
siteLanguage: en
