siteIcon: "/media/default-site-icon.png"
siteUrl: https://boldlypress.netlify.app
siteIconAlt: Rocket blasting off
siteName: BoldlyPress
siteImage: "https://boldlypress.netlify.app/media/default-site-image.jpg"
siteDescription: The React starter for DevBoldly.
siteImageAlt: Cute and cuddly kittens.
siteLanguage: en
