contactFormActionUrl: /
contactFormMethod: POST
contactFormNameAttribute: contactForm
contactFormAsyncEnabled: true
contactFormControls:
  fields:
    - initialValue: none
      label: Full Name
      nameAttribute: fullName
      placeholder: Enter your full name
      required: true
      requiredErrorText: This field is required.
      type: text
    - initialValue: none
      label: Email
      nameAttribute: emailAddress
      placeholder: Enter your email
      required: true
      requiredErrorText: This field is required.
      type: email
    - initialValue: none
      label: Message
      nameAttribute: message
      placeholder: Enter your message
      required: true
      requiredErrorText: This field is required.
      type: textarea
  submitButtonText: Send
