navbarLogo:
  navbarCustomLogoImage: /media/no-image.png
  navbarLogoDescriptionEnabled: true
  navbarLogoDescriptionText: <small>The serverless CMS for React developers.</small>
  navbarLogoGap: 10
  navbarLogoImageEnabled: true
  navbarLogoImageHeight: 30
  navbarLogoImageWidth: 30
  navbarLogoText: <span class="font-weight-bold">Boldly</span>Press
  navbarLogoTextEnabled: true
  navbarUseSiteIcon: true
  navbarHideDescriptionWhenScrolling: true
  navbarLogoOrderReversed: false
navbarPlacement: sticky-top
navbarFixedTopPadding: 0
navbarDropShadow: just-beyond
