googleAnalytics:
  analyticsEnabled: true
  trackingId: UA-123456789-1
  anonymize: false
  respectDNT: false
  scriptInHead: false
googleOAuthClientId: 932669268667-ptpd9g2buqb0qv56rk8ki8cpavedku83.apps.googleusercontent.com
buildStatusBadge:
  buildStatusBadgeImageUrl: https://api.netlify.com/api/v1/badges/6c4493db-5263-469c-a0d2-4e3194086bb3/deploy-status
  buildStatusBadgeImageAlt: Netlify Status
  buildStatusBadgeImageLink: https://app.netlify.com/sites/boldlypress/deploys
