seoTitleSeparator: ' - '
seoConfigurations:
  - seoConfigurationId: default-page-seo-configuration
    seoConfigurationName: Default Page SEO Configuration
    seoDescription: '{contentExcerpt}'
    seoTitle: '{contentTitle}'
