seoTitleSeparator: ' - '
seoConfigurations:
  - seoConfigurationId: index-seo-configuration
    seoConfigurationName: Index SEO Configuration
    seoDescription: '{siteDescription}'
    seoTitle: '{siteName}{seoTitleSeparator}{siteDescription}'
  - seoConfigurationId: default-page-seo-configuration
    seoConfigurationName: Default Page SEO Configuration
    seoDescription: '{contentExcerpt}'
    seoTitle: '{contentTitle}{seoTitleSeparator}{siteName}'
  - seoConfigurationId: default-post-seo-configuration
    seoConfigurationName: Default Post SEO Configuration
    seoDescription: '{contentExcerpt}'
    seoTitle: '{contentTitle}{seoTitleSeparator}{siteName}'
