siteMetadata:
  siteName: gatsby-starter-mdx-launchpad
  siteUrl: 'https://gatsby-starter-mdx-launchpad.netlify.app'
  siteDescription: gatsby-starter-mdx-launchpad
  siteIcon: /media/site-icon.png
  siteIconAlt: gatsby-starter-mdx-launchpad
  siteImage: '{siteUrl}/media/site-image.jpg'
  siteImageWidth: 1200
  siteImageHeight: 630
  siteImageAlt: gatsby-starter-mdx-launchpad
gatsbyPluginManifestOptions:
  name: gatsby-starter-mdx-launchpad
  shortName: gatsby-starter-mdx-launchpad
  startUrl: /
  themeColor: '#1167b1'
  backgroundColor: '#03254c'
  display: standalone
  customIcon: none # '/media/pwa-icon.png'
seoTitleFormat: '{contentTitle}{seoTitleSeparator}{siteName}'
seoTitleSeparator: ' - '
privatePagePathPrefix: private # Must not start or end with a slash
googleAnalyticsMeasurementId: none
disqusShortname: none
twitterSiteUsername: none