siteMetadata:
  siteIcon: "/media/site-icon.png"
  siteUrl: https://gatsby-starship.netlify.app
  siteIconAlt: gatsby-starship
  siteName: gatsby-starship
  siteImage: "{siteUrl}/media/site-image.jpg"
  siteImageWidth: 1200
  siteImageHeight: 630
  siteDescription: gatsby-starship
  siteImageAlt: gatsby-starship
gatsbyPluginManifestOptions:
  name: gatsby-starship
  shortName: gatsby-starship
  startUrl: "/"
  themeColor: "#1167b1"
  backgroundColor: "#03254c"
  display: standalone
  customIcon: none # "/media/pwa-icon.png"
seoTitleSeparator: ' - '
privatePagePathPrefix: private # Must not start or end with a slash
googleAnalyticsTrackingId: none
disqusShortname: none
twitterSiteUsername: none