shareHomePageEnabled: true
facebook:
  connectViaFacebookEnabled: false
  connectViaFacebookUrl: 'none'
  facebookPostSharingEnabled: true
twitter:
  connectViaTwitterEnabled: false
  connectViaTwitterUrl: 'none'
  twitterPostSharingEnabled: true
  twitterSiteUsername: 'none'
linkedIn:
  linkedInPostSharingEnabled: true
email:
  connectViaEmailEnabled: true
  connectViaEmailUrl: /contact
instagram: 
  connectViaInstagramEnabled: true
  connectViaInstagramUrl: 'https://www.instagram.com/justintothemoon/'