sharing:
  facebookPostSharingEnabled: true
  twitterPostSharingEnabled: true
  linkedInPostSharingEnabled: true
  shareHomePageEnabled: false
socialAccounts:
  - name: Instagram
    link: 'https://www.instagram.com/justintothemoon/'
    enabled: true
  - name: GitHub
    link: 'https://github.com/devboldly'
    enabled: true
  - name: Contact
    link: '/contact'
    enabled: true
twitterSiteUsername: 'none'