offlineSupportEnabled: true
showPromptWhenUpdateAvailable: true
updateAvailablePromptMessage: This application has been updated. Reload to display
  the latest version?
gatsbyPluginManifestOptions:
  name: "{siteName}"
  shortName: "{siteName}"
  startUrl: "/"
  themeColor: "#1167b1"
  backgroundColor: "#03254c"
  display: standalone
  icon:
    useSiteIcon: true
    customIcon: "/media/no-image.png"
